### ISSUE TITLE
Make test

### ISSUE THREAD

**Issue by fran-jo** [SanPen/fpotencia#7] opened 2016-09-27 17:01 UTC
Following the compilation steps and the previous issues I execute make test but I get no output:
fran_jo$ make test
make: *** No rule to make target `test'.  Stop.

Am I missing something?

Thanks!

**Comment by eveith** [comment] 2016-09-27 17:28
This is not quite what I would expect. You need to run `make test` from the same directory you've build fPotencia in, i.e., the one you issued `make` in.

You can also manually locate the `fpotencia_test` binary and run that. Note that the NRcurrent solver currently fails on the Lynn Powell testcase with attached generator; this is expected. All other tests should pass, however.

**Comment by fran-jo** [comment] 2016-09-28 14:28
@eveith I am confused with this, so here is what I found. After executing "_make test_" I found this folder:
_fpontecia/test/CMakeFiles/3.6.2/CompilerIdCXX/ that contains an a.out_. I guess this is the executable generated by "_make test_" command, am I right?
The ./a.out command does not show anything...

**Comment by eveith** [comment] 2016-09-28 15:45
No, sorry; the binary is really named `fpotencia_test`, and only so. If you've followed the instructions in the README, you'll find it in `Build/test/fpotencia_test`. This binary is built as part of the normal compilation with `make` and present *before* you issue `make test`. It will, however, only be present if GTest was detected during `cmake`. You might want to check that in your `CMakeCache.txt`.

**Comment by fran-jo** [comment] 2016-10-13 09:42
@eveith a little bit more on Mac OS X experience
After installing GTest with macports (sudo port install gtest), I get this error:

`Franciss-MacBook-Pro:build fran_jo$ make`
`[ 79%] Built target fpotencia`
`Scanning dependencies of target fpotencia_test`
`[ 83%] Building CXX object test/CMakeFiles/fpotencia_test.dir/SolverTest.cpp.o`
`[ 87%] Building CXX object test/CMakeFiles/fpotencia_test.dir/NRpolarSolverTest.cpp.o`
`[ 91%] Building CXX object test/CMakeFiles/fpotencia_test.dir/NRcurrentSolverTest.cpp.o`
`[ 95%] Building CXX object test/CMakeFiles/fpotencia_test.dir/main.cpp.o`
`[100%] Linking CXX executable fpotencia_test`
`ld: library not found for -lgtest`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make[2]: *** [test/fpotencia_test] Error 1`
`make[1]: *** [test/CMakeFiles/fpotencia_test.dir/all] Error 2`
`make: *** [all] Error 2`

I am "investigating" why I have this issue with -lgtest

Cheers!

**Comment by eveith** [comment] 2016-10-13 09:58
The issue is probably a question of `where did macports put libgtest.so?' Find
out where it is, add the path to your library search path, and you should be
done.

HTH.

**Comment by fran-jo** [comment] 2016-10-13 11:01
Ok! I think I solve it! 
I restarted the computer and then I add the following:
`export LIBRARY_PATH=/opt/local/lib:/opt/local/include/gtest`
which is the folder where macports installed the Gtest

`[ 79%] Built target fpotencia`
`[ 83%] Linking CXX executable fpotencia_test`
`[100%] Built target fpotencia_test`

**Comment by eveith** [comment] 2016-10-13 11:36
Yep, looks good. I'll close this issue for now. Holler if anything else bugs you wrt testing.

**Closed by eveith** 2016-10-13 11:36 UTC
